# Generated by Django 3.2.10 on 2022-06-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_building_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.CharField(default='備考欄', max_length=500, verbose_name='備考'),
            preserve_default=False,
        ),
    ]
