# Generated by Django 3.2.10 on 2022-06-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0003_building_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='備考'),
        ),
    ]
