# Generated by Django 3.2.10 on 2022-06-10 06:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_alter_building_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='生徒名')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_management.building', verbose_name='所属校舎')),
            ],
        ),
    ]
